const pets = [
  {
    id: 'pet1',
    type: 'Dog',
    species: 'Wolf Hybrid',
    sex: 'Male',
    color: 'White',
    name: 'Odin',
    owner: 'Keith Walker',
    img: 'https://www.instagram.com/p/BpnmgIFAKhF/media/?size=m',
    weight: 75,
    age: 10,
    isBoarded: true,
    notes: 'Bad Hips, Pain, Hard time walking',
  },
  {
    id: 'pet2',
    type: 'Dog',
    species: 'Border Collie',
    sex: 'Female',
    color: 'Black/White',
    name: 'Whisky',
    owner: 'Brittney Sullivan',
    img: 'https://www.instagram.com/p/BwOCy9WHwNF/media/?size=m',
    weight: 30,
    age: 4,
    isBoarded: true,
    notes: 'Un-spayed',
  },
  {
    id: 'pet3',
    type: 'Dog',
    species: 'Border Collie',
    sex: 'Male',
    color: 'Black/White',
    name: 'Grimm',
    owner: 'Brittney Sullivan',
    img: 'https://www.instagram.com/p/BwOCr_un3xK/media/?size=m',
    weight: 33,
    age: 2,
    isBoarded: true,
    notes: 'Atention Seeker',
  },
  {
    id: 'pet4',
    type: 'Tarantula',
    species: 'Theraphosa Stirmi',
    sex: 'Female',
    color: 'Brown',
    name: 'Gojira',
    owner: 'Brittney Sullivan',
    img: 'https://www.instagram.com/p/By8czJZgJAo/media/?size=m',
    weight: 0.25,
    age: 4,
    isBoarded: true,
    notes: 'DO NOT HANDLE',
  },
  {
    id: 'pet5',
    type: 'Tarantula',
    species: 'Psalmopoeus Irminia',
    sex: 'Female',
    color: 'Black/Orange',
    name: 'Raj',
    owner: 'Brittney Sullivan',
    img: 'https://www.instagram.com/p/ByqQJEwApiS/media/?size=m',
    weight: 33,
    age: 2,
    isBoarded: true,
    notes: 'DO NOT HANDLE',
  },
  {
    id: 'pet3',
    type: 'Lizard',
    species: 'Leapord Gecko',
    sex: 'Female/Male',
    color: 'Tan/Spotted',
    name: 'Gecko 1, Gecko 2',
    owner: 'Keith Walker, Brittney Sullivan',
    img: 'https://www.instagram.com/p/BxhakmcBCp_/media/?size=m',
    weight: 1,
    age: 1,
    isBoarded: false,
    notes: '2 geckos boarded together, Friendly, Caution when handling',
  },
];

export default pets;
